version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      username: ${MQTT_USERNAME}
      password: ${MQTT_PASSWORD}
      MQTT_HOST: ${MQTT_HOST}
    stdin_open: true
    tty: true
